install.packages("readxl")
library(readxl)
install.packages("fansi")
library(fansi)
install.packages("utf8")
library(utf8)
hospitalcosts <- read_excel("1555054100_hospitalcosts.xlsx")
View(hospitalCosts)
summary(hospitalCosts)
hist(hospitalCosts$AGE)
summary(as.factor(hospitalCosts$AGE))
aggregate(TOTCHG ~ AGE, FUN = sum, data = hospitalCosts)
max(aggregate(TOTCHG ~ AGE, FUN = sum, data = hospitalCosts))
which.max(summary(as.factor(hospitalCosts$APRDRG)))
diagnosiscost <- aggregate(TOTCHG ~ APRDRG, FUN = sum, data = hospitalCosts)
diagnosiscost
diagnosiscost[which.max(diagnosiscost$TOTCHG),]
summary(as.factor(hospitalCosts$RACE))
head(hospitalCosts)
hospitalCosts<-na.omit(hospitalCosts)
hospitalCosts$RACE<-as.factor(hospitalCosts$RACE)
model <- aov(TOTCHG ~ RACE, data = hospitalCosts)
model
summary(model)
summary(hospitalCosts$RACE)
model1 <- lm(TOTCHG ~ AGE + FEMALE, data = hospitalCosts)
hospitalCosts$FEMALE<-as.factor(hospitalCosts$FEMALE)
model1 <- lm(TOTCHG ~ AGE + FEMALE, data = hospitalCosts)
summary(model1)
summary(hospitalCosts$FEMALE)
head(hospitalCosts)
hospitalCosts$RACE<-as.factor(hospitalCosts$RACE)
model2 <- lm(TOTCHG ~ AGE + FEMALE + RACE, data = hospitalCosts)
summary(model2)
model3 <- lm(TOTCHG ~ ., data = hospitalCosts)
summary(model3)
